server:
  port: 18085

spring:
  # 数据源配置信息根据自己的数据库而定
  datasource:
    name: raisehand
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      driver‐class‐name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/raisehand?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      phy-max-use-count: 1000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  
  ## thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  mvc:
    static-path-pattern: /static/**
  
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
